// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgtsawsmyeoocwvhdktn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndHNhd3NteWVvb2N3dmhka3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTg2NjIsImV4cCI6MjA2MDgzNDY2Mn0.GOuwFE4x9ZIltAQR-zjfWyDQJHpOIz9FN_LtJpZbutQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);